### PR TITLE
replace grabGitRevision to grabRevision as it was simplified

### PR DESCRIPTION
**Pull request by maxulysse**

### CODE REVIEW

**Comment by ewels** [comment]
Nice! I might steal this ;)

**Comment by ewels** [comment]
```groovy
workflow.scriptId.substring(0,10)
```

Isn't this already printed in the Nextflow log?

```
N E X T F L O W  ~  version 0.23.4
Launching `../main.nf` [cranky_saha] - revision: 66ee28772e
```

I think the hash at the end (`66ee28772e`) is the start of the `scriptId`. Or at least it seemed the same to me when I stole your code just now ;)

**Comment by maxulysse** [comment]
Totally, but from what I understood that was the point of the grab_git_revision function made by NBIS, I'll make a PR on their repo.

**Comment by maxulysse** [comment]
Update with new containers to prepare for TRAVIS integration in CAW.

**Pull request merged**
